version: "3.2"

services:
  postgres:
    image: postgres:10.0
    hostname: postgres
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bard
      POSTGRES_PASSWORD: bard
      POSTGRES_DATABASE: bard

  api:
    build:
      context: .
    #image: barddata/bard:${BARD_TAG:-latest}
    #command: bard run -h 0.0.0.0 -p 5000 --with-threads --reload --debugger
    command: gunicorn --workers 2 --timeout 90 --bind 0.0.0:5000 --access-logfile - wsgi:application --reload
    ports:
      - "127.0.0.1:5000:5000"
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - "./bard:/bard/bard"
    environment:
      DAKOBED_DEBUG: "true"
      DAKOBED_PROFILE: "false"
      DAKOBED_SECRET_KEY: "development"
      BARD_DATABASE_URI: "postgresql://bard:bard@postgres:5432/bard"


volumes:
  archive-data: {}
  postgres-data: {}
  redis-data: {}
  elasticsearch-data: {}

